include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_super_parameters: false
    library_private_types_in_public_api: false

analyzer:
  # exclude:
  #   - "**/*.g.dart"
  #   - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore
