name: boilerplate
description: A flutter boilerplate project created using MobX and Provider.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # A
  another_flushbar: ^1.12.30
  auto_route: ^8.1.3
  # B
  # C
  cupertino_icons: ^1.0.8
  # D
  drift: ^2.18.0
  drift_dev: ^2.18.0
  dio: ^5.4.3+1
  # E
  # F
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^2.0.10+1
  # G
  get_it: ^7.2.0
  # H
  # I
  intl: ^0.19.0
  # J
  json_annotation: ^4.9.0
  # K
  # L
  lottie: ^3.1.0
  # M
  mobx: ^2.1.4
  # N
  # O
  # P
  path_provider: ^2.1.3
  path: ^1.9.0
  # Q
  # R
  # S
  shared_preferences: ^2.2.3
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  sqlite3_flutter_libs: ^0.5.21
  sqlite3: ^2.4.3
  # T
  talker_flutter: ^4.2.0
  talker_dio_logger: ^4.2.0
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  # Y
  # Z

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.2

  auto_route_generator: ^8.0.0
  slang_build_runner: ^3.30.0
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.4.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.4.10
  build_web_compilers: ^4.0.10
  build: ^2.4.1
  analyzer: ^6.4.1

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/
  - assets/translations/

  fonts:
    - family: Comfortaa
      fonts:
      - asset: assets/fonts/Comfortaa-Regular.ttf
        weight: 500
      - asset: assets/fonts/Comfortaa-Medium.ttf
        weight: 700
      - asset: assets/fonts/Comfortaa-Bold.ttf
        weight: 900

flutter_gen:
  output: lib/generated/
  line_length: 120

  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml
